/**
 * fireyejsRunner — Token generation and infrastructure.
 *
 * bx-ua: Generated by bxUaGenerator.ts — a pure Node.js implementation
 *   that replicates the AWSC fireyejs.js token format without Playwright.
 *   Matches the real token: "231!" + base64(900 bytes) = 1204 chars.
 *
 * bx-pp: SHA-256 payload hash fallback (opcode 58 needs real AWSC).
 *
 * Cookie refresh: Playwright browser navigates chat.qwen.ai to refresh
 *   acw_tc and other WAF session cookies. This is the only remaining
 *   browser dependency — runs once per 30 min per account.
 */
import { resolve } from 'path';
import { getBxUaToken, resetCache } from './bxUaGenerator.ts';
import { logStore } from './logStore.ts';
import { QWEN_API_BASE } from './qwen.ts';
import { tokenCache } from './tokenCache.ts';

// ─── Constants ───────────────────────────────────────────────────────────────

const BX_UA_TTL_MS = 15 * 60 * 1000; // 15 min
const DEFAULT_FIREYEJS_PATH = resolve(process.cwd(), 'fireyejs.js');

// ─── bx-ua generation ────────────────────────────────────────────────────────
// Pure Node.js via bxUaGenerator.ts — no browser needed.
// Token matches real AWSC fireyejs.js output format exactly.

/**
 * Generate (or retrieve cached) bx-ua token.
 *
 * @returns The bx-ua token string (e.g. "231!<base64>") or null
 */
export async function generateBxUa(): Promise<string | null> {
  // Check shared cache first
  const cached = tokenCache.get('bx-ua');
  if (cached) return cached;

  try {
    const token = getBxUaToken();

    if (token && token.startsWith('231!')) {
      tokenCache.set('bx-ua', token, BX_UA_TTL_MS);
      logStore.log('info', 'fireyejs', `bx-ua generated via bxUaGenerator (${token.length} chars, TTL ${BX_UA_TTL_MS / 60000} min)`);
      return token;
    }

    logStore.log('warn', 'fireyejs', 'bx-ua generated but invalid format');
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('error', 'fireyejs', `bx-ua generation failed: ${msg}`);
    return null;
  }
}

export function resetBxUaCache(): void {
  tokenCache.delete('bx-ua');
  resetCache();
}

// ─── bx-pp generation (Phase C) ──────────────────────────────────────────────

/**
 * Generate a bx-pp per-request signature.
 *
 * bx-pp is normally generated by fireyejs opcode 58. Since the real fireyejs
 * requires the AWSC browser environment, we use a SHA-256 payload hash as
 * fallback. Testing confirmed this works: the models endpoint returned 200.
 *
 * TODO: reverse-engineer opcode 58 from fireyejs.js for bx-pp generation
 * that matches what the real browser produces.
 */
export async function generateBxPp(payload?: string): Promise<string | null> {
  // Check if we have a real bx-pp template from the browser (extracted via
  // refreshCookiesViaBrowser). Use it in preference to the hash fallback.
  const browserBxPp = tokenCache.get('bx-pp-template');
  if (browserBxPp) {
    logStore.log('debug', 'fireyejs', `bx-pp using browser-extracted template (${browserBxPp.length} chars)`);
    return browserBxPp;
  }

  // ponytail: hash fallback until opcode 58 reverse-engineered
  try {
    const data = new TextEncoder().encode(payload || Date.now().toString());
    const hash = await crypto.subtle.digest('SHA-256', data);
    const hashHex = Array.from(new Uint8Array(hash))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
      .slice(0, 32);
    logStore.log('debug', 'fireyejs', 'bx-pp generated (hash fallback)');
    return hashHex;
  } catch {
    return null;
  }
}

// ─── Cookie refresh via browser ─────────────────────────────────────────────
//
// Two backends supported (browser_oxide preferred, cloakbrowser fallback):
//
// 1. browser_oxide — Rust stealth engine via Python bindings (PyO3).
//    Native BoringSSL TLS, V8 JS, ~15x lighter than Chrome.
//    Invoked via `python3 -c "..."` subprocess.
//
// 2. cloakbrowser — stealth Chromium (2GB download, ~2GB memory).
//    Required for login (because browser_oxide doesn't have profile management).
//    Fallback when browser_oxide is unavailable.

let playwrightBrowser: any = null;
let lastCookieRefreshBackend: 'browser_oxide' | 'cloakbrowser' | null = null;

async function getBrowser(): Promise<any> {
  if (playwrightBrowser && !(playwrightBrowser as any)._closed) {
    return playwrightBrowser;
  }
  // Try browser_oxide (Rust stealth engine via Python) first
  try {
    const { isBrowserOxideAvailable } = await import('./browserOxidePython.ts');
    if (await isBrowserOxideAvailable()) {
      logStore.log('debug', 'fireyejs', 'Using browser_oxide (Rust/Python) backend for cookie refresh');
      lastCookieRefreshBackend = 'browser_oxide';
      return createBrowserOxideProxyBrowser();
    }
  } catch (err: any) {
    logStore.log('debug', 'fireyejs', `browser_oxide unavailable: ${err.message}`);
  }
  // Fallback to standard Chromium (via cloakbrowser)
  const { chromium } = await import('playwright');
  playwrightBrowser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
  });
  lastCookieRefreshBackend = 'cloakbrowser';
  return playwrightBrowser;
}

/**
 * Create a proxy "browser" object that uses browser_oxide via Python.
 * Implements the subset of the Playwright Browser API used by
 * refreshCookiesViaBrowser (newPage, cookies, close).
 */
function createBrowserOxideProxyBrowser(): any {
  return {
    _closed: false,
    _isBrowserOxideProxy: true,
    async newPage(): Promise<any> {
      return createBrowserOxideProxyPage();
    },
    async close(): Promise<void> {
      this._closed = true;
    },
  };
}

/**
 * Create a proxy Page that uses browser_oxide via Python.
 */
function createBrowserOxideProxyPage(): any {
  return {
    _isBrowserOxideProxy: true,
    async goto(url: string, opts?: any): Promise<void> {
      try {
        const { browserOxideNavigate } = await import('./browserOxidePython.ts');
        await browserOxideNavigate(url, 'chrome');
      } catch (err: any) {
        logStore.log('debug', 'fireyejs', `[browser_oxide] navigate to ${url} failed: ${err.message}`);
      }
    },
    async evaluate(fn: any): Promise<any> {
      // For browser_oxide, evaluate requires a separate Python call.
      // Cookie refresh doesn't need evaluate, so return empty.
      return '';
    },
    async waitForTimeout(ms: number): Promise<void> {
      await new Promise((r) => setTimeout(r, ms));
    },
    async close(): Promise<void> {
      // no-op
    },
  };
}

async function closeBrowser(): Promise<void> {
  // Don't close browser_oxide (Python subprocess manages its own lifecycle).
  // Only close standalone Chromium we created here.
  if (playwrightBrowser && lastCookieRefreshBackend === 'cloakbrowser') {
    try {
      await playwrightBrowser.close();
    } catch {
      // already closed
    }
  }
  playwrightBrowser = null;
}

const COOKIE_REFRESH_TTL_MS = 30 * 60 * 1000; // 30 min

/**
 * Refresh cookies for an account by navigating chat.qwen.ai in a real browser.
 * Also extracts real bx-ua and bx-pp tokens from the page's AWSC localStorage
 * (the proper opcode-58 signature, not the hash fallback).
 *
 * @param cookieStr - Current saved cookies (may be stale)
 * @returns Fresh cookie string or null
 */
export async function refreshCookiesViaBrowser(cookieStr: string): Promise<string | null> {
  let page: any = null;
  try {
    const browser = await getBrowser();
    page = await browser.newPage();

    // For browser_oxide proxy: there's no context().cookies() —
    // browser_oxide doesn't track per-context cookies the same way.
    // Return the input cookie string (preserving what we already had)
    // and rely on the stealth fetch via browser_oxide's native TLS.
    if (page._isBrowserOxideProxy) {
      logStore.log('debug', 'fireyejs', 'Using browser_oxide (Rust/Python) for cookie refresh — preserving existing cookies');
      await page.goto(QWEN_API_BASE).catch(() => {});
      await new Promise((r) => setTimeout(r, 2000));
      if (cookieStr) {
        logStore.log('info', 'fireyejs', `Cookies preserved via browser_oxide: ${cookieStr.substring(0, 60)}...`);
        return cookieStr;
      }
      return null;
    }

    if (cookieStr) {
      const cookies = cookieStr.split(';').map((pair: string) => {
        const [name, ...rest] = pair.trim().split('=');
        return { name: name.trim(), value: rest.join('=').trim(), domain: '.chat.qwen.ai', path: '/' };
      });
      await page
        .context()
        .addCookies(cookies)
        .catch(() => {});
    }

    await page.goto(QWEN_API_BASE, { waitUntil: 'load', timeout: 25_000 }).catch(() => {});
    // Wait for WAF challenge to resolve (up to 15s)
    for (let i = 0; i < 15; i++) {
      const html = await page.evaluate(() => document.documentElement?.innerHTML || '').catch(() => '');
      if (!html.includes('aliyun_waf')) break;
      await new Promise((r) => setTimeout(r, 1000));
    }

    // ── Extract real bx-ua and bx-pp tokens from AWSC ────────────────
    try {
      const awscTokens = await page.evaluate(() => {
        const result: { bxUa: string | null; bxPp: string | null } = { bxUa: null, bxPp: null };
        try {
          for (const key of Object.keys(localStorage)) {
            const lower = key.toLowerCase();
            const value = localStorage.getItem(key) || '';
            if (!result.bxUa && (lower.includes('bxua') || lower.includes('bx_ua') || lower === 'awsc_bxua')) {
              if (value && value.length > 100) result.bxUa = value;
            }
            if (!result.bxPp && (lower.includes('bxpp') || lower.includes('bx_pp') || lower === 'awsc_bxpp')) {
              if (value && value.length > 10) result.bxPp = value;
            }
          }
          for (const key of Object.keys(sessionStorage)) {
            const lower = key.toLowerCase();
            const value = sessionStorage.getItem(key) || '';
            if (!result.bxUa && (lower.includes('bxua') || lower.includes('bx_ua'))) {
              if (value && value.length > 100) result.bxUa = value;
            }
            if (!result.bxPp && (lower.includes('bxpp') || lower.includes('bx_pp'))) {
              if (value && value.length > 10) result.bxPp = value;
            }
          }
          const awsc: any = (window as any).AWSC || (window as any)._AWSC;
          if (awsc && typeof awsc.getToken === 'function') {
            try {
              const token = awsc.getToken('bxua');
              if (token && !result.bxUa) result.bxUa = token;
            } catch {}
            try {
              const pp = awsc.getToken('bxpp');
              if (pp && !result.bxPp) result.bxPp = pp;
            } catch {}
          }
        } catch (e) {
          // ignore
        }
        return result;
      });

      if (awscTokens?.bxUa) {
        tokenCache.set('bx-ua', awscTokens.bxUa, BX_UA_TTL_MS);
        logStore.log('info', 'fireyejs', `bx-ua extracted from browser AWSC (${awscTokens.bxUa.length} chars)`);
      }
      if (awscTokens?.bxPp) {
        tokenCache.set('bx-pp-template', awscTokens.bxPp, 60_000);
        logStore.log('info', 'fireyejs', `bx-pp extracted from browser AWSC (${awscTokens.bxPp.length} chars)`);
      }
    } catch (err) {
      logStore.log('debug', 'fireyejs', `bx-ua/bx-pp extraction from browser failed: ${(err as Error).message}`);
    }

    const freshCookies = await page.context().cookies();
    const cookieMap = new Map<string, string>();
    for (const c of freshCookies) {
      cookieMap.set(c.name, c.value);
    }

    const freshCookieStr = Array.from(cookieMap.entries())
      .map(([n, v]) => `${n}=${v}`)
      .join('; ');

    if (freshCookieStr) {
      logStore.log('info', 'fireyejs', `Cookies refreshed via browser: ${freshCookieStr.substring(0, 60)}...`);
      return freshCookieStr;
    }
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('warn', 'fireyejs', `Cookie refresh via browser failed: ${msg.substring(0, 100)}`);
    return null;
  } finally {
    if (page) {
      try {
        await page.close();
      } catch {
        /* ignore */
      }
    }
  }
}
